--getting into SQL: using SELECT 

--zadanie 1.1
SELECT *
FROM SALGRADE
--wyszlo ok

--zad 1.2
SELECT *
FROM EMP
-- w skrypcioe nie sa uporadkowane

--zad 1.3
SELECT *
FROM EMP 
WHERE (SAL >= 1000) AND (SAL <= 2000)
--dziala\

--zad 1.4
SELECT *
FROM DEPT
--dziala

--zadb 1.5
SELECT DISTINCT JOB 
FROM EMP

--ZAD 1.6
SELECT JOB , ENAME
FROM EMP
WHERE (DEPTNO = 10 OR DEPTNO= 20)
ORDER BY ENAME ASC

--ZAD 1.7
SELECT ENAME
FROM EMP
WHERE (DEPTNO = 20 AND JOB LIKE'CLERK')

--ZAD 1.8
SELECT ENAME, SAL, JOB
FROM EMP
WHERE MGR IS NOT NULL

--ZAD 1.9
SELECT ENAME, SAL
FROM EMP

--ZAD 1.10
SELECT ENAME, DEPTNO
FROM EMP
WHERE (HIREDATE>= '1982-01-01' AND HIREDATE <= '1982-12-31') 

--ZAD 1.11
SELECT ENAME, SAL*12 AS ANNUAL, COMM
FROM EMP 
WHERE (SAL > COMM AND COMM IS NOT NULL)
ORDER BY SAL DESC, ENAME ASC 

--ZAD 1.12
SELECT 'PRACOWNIK ' + ENAME + 'PRACUJE' + CAST(DEPTNO as varchar(10)) + 'OD ' + CAST(HIREDATE as varchar(10)) 
FROM EMP
--zad 1.13

SELECT ENAME
FROM EMP
WHERE ENAME like '_LA%'

--zad 1.14
SELECT ENAME, DATEDIFF ( "YEAR",  HIREDATE, getdate()) ROZNICA_LATA
FROM EMP

--ZAD 1.15
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE,  SAL,  COMM, DEPTNO
FROM EMP
WHERE HIREDATE < '1981-01-01'
