-- Using conjuction and intersection of tables

--ZAD 3.1
SELECT DEPT.DNAME, ENAME
FROM EMP INNER JOIN DEPT ON DEPT.DEPTNO=EMP.DEPTNO
ORDER BY DEPT.DNAME;
 
 --ZAD 3.2
 SELECT EMP.ENAME, DEPT.DEPTNO, DNAME
 FROM DEPT INNER JOIN EMP ON DEPT.DEPTNO=EMP.DEPTNO
 ORDER BY DEPT.DEPTNO

 --ZAD 3.3
 SELECT SAL, ENAME, LOC, DNAME
 FROM DEPT INNER JOIN EMP ON DEPT.DEPTNO=EMP.DEPTNO
 WHERE SAL >1500 

 --ZAD 3.4
 SELECT ENAME, JOB, SAL, GRADE
 FROM EMP INNER JOIN SALGRADE ON EMP.SAL>=SALGRADE.GRADE

 --zad 3.5
 SELECT ENAME, JOB, SAL, GRADE
 FROM EMP INNER JOIN SALGRADE ON EMP.SAL>=SALGRADE.GRADE
 WHERE GRADE=3
 --ZAD 3.6
 SELECT ENAME, SAL, LOC
 FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO 
 WHERE LOC='DALLAS'

 --ZAD 3.7
 SELECT ENAME, JOB, SAL, GRADE, DNAME
 FROM DEPT JOIN EMP ON DEPT.DEPTNO=EMP.DEPTNO JOIN SALGRADE ON EMP.SAL>=SALGRADE.GRADE
 WHERE JOB <> 'CLERK'
 ORDER BY SAL


 --ZAD 3.8
 SELECT S.ENAME AS S, P.ENAME AS P 
 FROM EMP P JOIN EMP S  ON S.EMPNO=P.MGR
 