-- using qualified commands to intersect or conjuct a table and sort data

 --ZAD 4.1
 SELECT DEPT.DEPTNO, DNAME
FROM DEPT LEFT JOIN EMP ON DEPT.DEPTNO= EMP.DEPTNO 
WHERE JOB IS NULL
--ZAD 4.2
SELECT S.ENAME AS S, S.EMPNO AS SZ, P.ENAME AS P, P.EMPNO AS PR 
FROM EMP P JOIN EMP S  ON S.EMPNO=P.MGR

--ZAD 4.3
SELECT S.ENAME AS S, S.EMPNO AS SZ, P.ENAME AS P, P.EMPNO AS PR 
FROM EMP P LEFT JOIN EMP S  ON S.EMPNO=P.MGR
--ZAD 4.4 
SELECT JOB
FROM EMP
WHERE HIREDATE BETWEEN '1982-01-01' AND '1982-06-30'
INTERSECT
SELECT JOB
FROM EMP
WHERE HIREDATE BETWEEN '1983-01-01' AND '1983-06-30'

 --ZAD 4.5
 SELECT  S.ENAME AS S, S.EMPNO AS SZ, S.HIREDATE, P.ENAME AS P, P.EMPNO AS PR, P.HIREDATE  
 FROM EMP P JOIN EMP S ON S.EMPNO=P.MGR
 WHERE S.HIREDATE> P.HIREDATE

 --ZAD 4.7
 SELECT  S.ENAME, AS S, S.EMPNO AS SZ, S.HIREDATE, P.ENAME AS P, P.EMPNO AS PR, P.HIREDATE
 FROM EMP P FULL OUTER JOIN EMP S ON S.EMPNO=P.MGR

 --ZAD 4.8
 SELECT  ISNULL( S.ENAME, 'NIE MA SZEFA') AS S, S.EMPNO AS SZ, S.HIREDATE, P.ENAME AS P, P.EMPNO AS PR, P.HIREDATE
 FROM EMP P FULL OUTER JOIN EMP S ON S.EMPNO=P.MGR
