--other applications of much more advanced commands
-- using order at comands ( FROM and JOINs > WHERE > GROUP BY > HAVING > SELECT > DISTINCT > ORDER BY > LIMIT / OFFSET)

--ZAD 6.1 WYBIERA OKREONE POZIOMY, PODSUMOWANIE DEP I STANOWISK
SELECT DEPTNO, JOB, GROUPING(DEPTNO), GROUPING(JOB), SUM(SAL), GROUPING_ID (JOB)
FROM EMP
GROUP BY CUBE(DEPTNO, JOB)
HAVING GROUPING_ID(DEPTNO, JOB) IN (2,1) 

SELECT S.ENAME, S.DEPTNO, SUM(P.SAL)
FROM EMP P JOIN EMP S ON P.MGR = S.EMPNO
GROUP BY ROLLUP(S.DEPTNO, S.ENAME)
ORDER BY 1,2

--ZAD 6.2
SELECT S.ENAME, S.DEPTNO, SUM(P.SAL)
FROM EMP P JOIN EMP S ON P.MGR=S.EMPNO
GROUP BY CUBE(S.DEPTNO, S.ENAME)
ORDER BY 1,2

--ZAD 6.3
SELECT DNAME, JOB, ENAME, COUNT(*), SUM(SAL)

FROM EMP JOIN DEPT ON EMP.DEPTNO= DEPT.DEPTNO
GROUP BY ROLLUP (DNAME, JOB, ENAME)

--ZAD 6.4
SELECT DNAME, JOB, COUNT(*), SUM(SAL)
FROM EMP JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO
GROUP BY ROLLUP(DNAME, JOB)


--ZAD 7.1 DATEPART("WEEKDAY", GETDATE())DATEIFF("QUARTER", '1991-01-01, GETDATE()) RZNICA MIEDZY DATAMI, DATA PRZYSZLA; DATEADD("QUARTER", 12, '1991-01-01')
SELECT ENAME, HIREDATE, SAL,
CASE 
WHEN DATEADD("YEAR", 38, '1981-01-01')= '2019-01-01' THEN SAL+1000
WHEN  DATEADD("YEAR", 37, '1981-01-01')= '2018-01-01' THEN SAL + 700
WHEN DATEADD("YEAR", 36, '1981-01-01')= '2017-01-01'  THEN SAL + 500
END [NOWA PENSJA] 
FROM EMP

--ZAD 7.2
SELECT ENAME, HIREDATE, SAL,
CASE
	WHEN DATEPART("YEAR", HIREDATE)= '1981' THEN CAST(SAL+1000 AS VARCHAR(MAX))
	WHEN DATEPART("YEAR", HIREDATE)= '1982' THEN 
		CASE WHEN DATEPART("WEEKDAY", HIREDATE)= '3'  THEN 'UMOW SPOTKANIE NA NASTEPNY WTOREK'
			 WHEN DATEPART("WEEKDAY", HIREDATE)<> '3' THEN 'UMOW SPOTKANIE NA NAJBLIZSZY WTOREK'
		END
	ELSE 'WYSLIJ MAILA Z GRATULACJAMI'
	END [ZADANIE]
FROM EMP


